version: "3.8"


services:
  database:
    image: mongo:latest
    container_name: blog-database
    ports:
      - 27017:27017
    restart: always
    networks:
      - personal-net
    volumes:
      - blog-data:/data/db
    
  database_gui:
    image: mongo-express
    container_name: blog-database-gui
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - database
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    networks:
      - personal-net

  backend:
    build: ./lets-blog-backend
    container_name: blog-backend
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - database
    environment:
      DATABASE: mongodb://database:27017/blog
    networks:
      - personal-net
    volumes:
      - ./lets-blog-backend:/app

  frontend:
    build: ./lets-blog
    container_name: blog-frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    networks:
      - personal-net
    volumes:
      - ./lets-blog:/app


networks:
  personal-net:
    driver: bridge


volumes:
  blog-data:

