version: "3.8"
services:
  database:
    image: mongo:latest
    container_name: blog-database
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      AUTH: admin
  backend:
    build: ./lets-blog-backend
    container_name: blog-backend
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - database
    environment:
      DATABASE: mongodb://admin:admin@database:27017
  frontend:
    build: ./lets-blog
    container_name: blog-frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
